### PR TITLE
Added 'bend resolution' slider

### PR DESCRIPTION
**Pull request by Archonic944**
This allows for pitch bend to be quantized into semitones (or smaller increments) for a more 'chipped' feel.

Things to consider:

 - The slider might not look good. I am a JUCE novice, but I still tried my best.
 - The pitch of a tonal voice can sound slightly off when not using bend resolution values of either 0 or 1. I honestly don't think the values in the middle are that useful; they could just be check marks.

I hope this plugin is still being maintained! A ton of people (like me) rely on it for a simple, cross-platform chiptune sound that isn't crazy expensive or using an emulator. :)

### CODE REVIEW

**Comment by Archonic944** [comment]
Changed this a little bit; it's no longer a slider, it's now 2 checkboxes. check commit description for more details.

**Comment by yokemura** [comment]
Thanks for your pull request, and i'm sorry for not responding for months.

You can get what you want with Custom Envelopes or Monophonic Mode.

By specifying series of semitones to Custom Pitch Envelope you can get the auto bending with semitone restriction.  On top of that you can also have it time quantized as well.  I believe the time quantization is as well important as the pitch quantization for a real chip feelings.

With Monophonic Mode you can change the pitch without restarting the envelope by overlapping the notes slightly.  To apply a quantized pitch bend this will be easier and you'll have more granularity over the transition.

I know these methods are a bit more cumbersome than your proposal, but I want to be somewhat thoughtful in adding more functionality to my plugin.

**Comment by Archonic944** [comment]
Thank you for the reply. I get that you don't want to fill up your plugin with unnecessary features, so it's OK that you don't want to merge my change. Although, I do kind of regret the way I went about this. If I had to do it again, I think I would just add a checkbox to quantize the automatic _portamento_, not auto or pitch bend. The only way to do that is this (image), and it would force you to not use the built-in portamento option:

image

Is there a way to do this within the current plugin? And do you think that would be a good proposal instead?

**Comment by yokemura** [comment]
I believe that my suggestion also works with Portamento as well.
Just set the Monophonic Mode to Legato, and no interporation of pitch will happen while the envelope and the wave phase retained.

**Comment by Archonic944** [comment]
Ok, thank you for the tip.

**Pull request closed without merging**
